export const colors = {
    primary: "#FF6347", // Tomato
    secondary: "#4682B4", // SteelBlue
    background: "#F0F8FF", // AliceBlue
    text: "#000000", // Black
    border: "#D3D3D3", // LightGray
    error: "#FF4500", // OrangeRed
    success: "#32CD32", // LimeGreen
    warning: "#FFD700", // Gold
    info: "#1E90FF", // DodgerBlue
    light: "#F5F5F5", // WhiteSmoke
    dark: "#696969", // DimGray
    muted: "#808080", // Gray
    accent: "#FF69B4", // HotPink
    highlight: "#ADFF2F", // GreenYellow
    shadow: "#000000", // Black
    transparent: "rgba(0, 0, 0, 0)", // Transparent
    white: "#FFFFFF", // White
    black: "#000000", // Black
    gray: "#808080", // Gray
    lightGray: "#D3D3D3", // LightGray
    darkGray: "#A9A9A9", // DarkGray
    blue: "#0000FF", // Blue
    red: "#FF0000", // Red
    green: "#008000", // Green
    yellow: "#FFFF00", // Yellow
    orange: "#FFA500", // Orange
    purple: "#800080", // Purple
    pink: "#FFC0CB", // Pink
    brown: "#A52A2A", // Brown
    teal: "#008080", // Teal
    navy: "#000080", // Navy
    olive: "#808000", // Olive
    maroon: "#800000", // Maroon
    silver: "#C0C0C0", // Silver
    gold: "#FFD700", // Gold
    coral: "#FF7F50", // Coral
    salmon: "#FA8072", // Salmon
    lavender: "#E6E6FA", // Lavender
    mint: "#98FF98", // Mint
    peach: "#FFDAB9", // Peach
    plum: "#DDA0DD", // Plum
    khaki: "#F0E68C", // Khaki
    ivory: "#FFFFF0", // Ivory
    beige: "#F5F5DC", // Beige
    wheat: "#F5DEB3", // Wheat
    lavenderBlush: "#FFF0F5", // LavenderBlush
    lightCyan: "#E0FFFF", // LightCyan
    lightGoldenrodYellow: "#FAFAD2", // LightGoldenrodYellow
    lightPink: "#FFB6C1", // LightPink

}